// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWLYKvfDTRPbzTNTZ6vx6PKdRx3guh_dY',
    appId: '1:1038788584473:web:538b1ba503938c2ac8b688',
    messagingSenderId: '1038788584473',
    projectId: 'chatapp-a8169',
    authDomain: 'chatapp-a8169.firebaseapp.com',
    storageBucket: 'chatapp-a8169.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkut2C6qq0y1bcGZ5QFuHnERN-hUHQV_0',
    appId: '1:1038788584473:android:cd5eaecb16442cf4c8b688',
    messagingSenderId: '1038788584473',
    projectId: 'chatapp-a8169',
    storageBucket: 'chatapp-a8169.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFUrABK3VPMqE0NalegoFPsRMJaKkVt6M',
    appId: '1:1038788584473:ios:b4fb4479eaa37423c8b688',
    messagingSenderId: '1038788584473',
    projectId: 'chatapp-a8169',
    storageBucket: 'chatapp-a8169.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFUrABK3VPMqE0NalegoFPsRMJaKkVt6M',
    appId: '1:1038788584473:ios:b4fb4479eaa37423c8b688',
    messagingSenderId: '1038788584473',
    projectId: 'chatapp-a8169',
    storageBucket: 'chatapp-a8169.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWLYKvfDTRPbzTNTZ6vx6PKdRx3guh_dY',
    appId: '1:1038788584473:web:5a98231b83e93fb4c8b688',
    messagingSenderId: '1038788584473',
    projectId: 'chatapp-a8169',
    authDomain: 'chatapp-a8169.firebaseapp.com',
    storageBucket: 'chatapp-a8169.appspot.com',
  );

}